version: "2"

services:
  zeebe:
    image: camunda/zeebe:0.21.1
    ports:
      - "26500:26500"
      - "9600:9600"

  node:
    image: node:12.8-alpine
    ports:
      - "5601:5601"
    command: >
      sh -c "npm install &&
             npm run build &&
             npm start"
    depends_on:
      - zeebe
